version: '3.9'

services:
  backend:
    build:
      context: .
      target: install-dependencies
    command: npm start
    restart: unless-stopped
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=info
